version: '3.8'

services:

    app:
        image: "ghcr.io/${{ github.repository_owner }}/model_service:latest"
        container_name: dev_model_service
        ports:
            - "8004:81"
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://192.168.1.150:9000
            - MLFLOW_TRACKING_URI=http://192.168.1.150:5000
