vars:
  - metadata/download_config.json

stages:

  load_historical_data:
    foreach: ${pollutants}
    do:
      cmd: python src/data/data_loading_historical.py ${item} 8
      deps:
        - metadata/download_config.json
      outs:
        - data/raw/historical_data_eea/${country}_${item}

  merge_data:
    foreach: ${pollutants}
    do:
      cmd: python src/data/data_raw_merge.py ${item}
      deps:
        - data/raw/historical_data_eea/
        - data/raw/updated_data_eea/
