  on:
    push:
      branches:
        - '*'
  jobs:
    build_a:
      runs-on: self-hosted #ubuntu-latest
      steps:
        - uses: actions/cache@v2
          id: cache-venv
          with:
            python-version: '3.x'
            path: |
              venv/
              .cache/pip
            key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
            restore-keys: |
              ${{ runner.os }}-venv-
        - run: |
            python --version
            python -m venv ./venv
            source ./venv/bin/activate
            pip install -r requirements.txt
          if: steps.cache-venv.outputs.cache-hit != 'true'
        - run: echo "This job will be run first."

    type_test:
      runs-on: self-hosted
      needs: [build_a]
      steps:
        - run: echo "This job will run after build_a have finished"

    test_b:
      runs-on: self-hosted
      needs: [build_a]
      steps:
        - run: echo "This job will run after build_a have finished, it is parallel test_a"

    deploy_ab:
      runs-on: self-hosted
      needs: [type_test, test_b]
      steps:
        - run: echo "This job will run after test_a and test_ab is complete"