  on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - main

  jobs:
    build_one:
      runs-on: self-hosted
      steps:
        - name: Install Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            virtualenvs-create: true
            virtualenvs-in-project: true

        - uses: actions/checkout@v3
        - name: Cache dependencies
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
            path: .venv
            key: venv-${{ runner.os }}-mycache-v1-${{ hashFiles('**/poetry.lock') }}

        - name: Install dependencies
          if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
          run: poetry install --no-interaction --no-root

        - name: Run Black
          run: poetry run black --line-length 88 --check .

#        - name: Linter
#          run: poetry run flake8 --max-line-length 88 --ignore F401,F841,W503 .

        - name: Pytest
          run: |
            poetry run dvc pull
            poetry run pytest --disable-warnings
