  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

  jobs:
    build_a:
      runs-on: ubuntu-latest
      steps:
        - name: Install Poetry
          uses: snok/install-poetry@v1
        - uses: actions/checkout@v3
        - name: Cache dependencies
          uses: actions/cache@v3
          id: cache-venv
          with:
            path: |
              venv/
              .cache/pip
            key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
            restore-keys: |
              ${{ runner.os }}-venv-
        - name: Install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: poetry install --no-interaction --no-root

    type_test:
      runs-on: ubuntu-latest
      needs: [build_a]
      steps:
        - run: echo "This job will run after build_a have finished"

    test_b:
      runs-on: ubuntu-latest
      needs: [build_a]
      steps:
        - run: echo "This job will run after build_a have finished, it is parallel test_a"

    deploy_ab:
      runs-on: ubuntu-latest
      needs: [type_test, test_b]
      steps:
        - run: echo "This job will run after test_a and test_ab is complete"